Runnning hand detection
[20250715;15:54:03] [HandJointsDetector:run] [INF] ====================================================================================================
[20250715;15:54:03] [HandJointsDetector:run] [INF] Starting Hand Landmarks Detection for 20250704_202733
[20250715;15:54:03] [HandJointsDetector:run] [INF] ====================================================================================================
[20250715;15:54:03] [HandJointsDetector:detect_mp_handmarks] [INF] >>>>>>>>>> Running MediaPipe Hand Detection <<<<<<<<<<
[DEBUG] Object group layer not loaded.
  0%|                                                                         | 0/8 [00:00<?, ?it/s]WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1752566045.082177 2790373 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1752566045.182388 2790598 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 565.57.01), renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1752566045.957245 2790374 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1752566046.049955 2790756 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 565.57.01), renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1752566046.802174 2790375 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1752566046.915347 2790799 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 565.57.01), renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1752566047.649020 2790376 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1752566047.780885 2790801 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 565.57.01), renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
I0000 00:00:1752566048.476124 2790373 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1752566048.542465 2790803 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 565.57.01), renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Process ForkProcess-3:
Process ForkProcess-2:
Process ForkProcess-4:
Process ForkProcess-1:
Traceback (most recent call last):
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
self.config: {'max_num_hands': 0, 'min_hand_detection_confidence': 0.1, 'min_tracking_confidence': 0.5, 'min_hand_presence_confidence': 0.5, 'running_mode': 'video', 'frame_rate': 30, 'model_asset_path': 'config/checkpoints/mediapipe/hand_landmarker.task', 'device': 'cuda'}
DEBUG: 0
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
self.config: {'max_num_hands': 0, 'min_hand_detection_confidence': 0.1, 'min_tracking_confidence': 0.5, 'min_hand_presence_confidence': 0.5, 'running_mode': 'video', 'frame_rate': 30, 'model_asset_path': 'config/checkpoints/mediapipe/hand_landmarker.task', 'device': 'cuda'}
DEBUG: 0
self.config: {'max_num_hands': 0, 'min_hand_detection_confidence': 0.1, 'min_tracking_confidence': 0.5, 'min_hand_presence_confidence': 0.5, 'running_mode': 'video', 'frame_rate': 30, 'model_asset_path': 'config/checkpoints/mediapipe/hand_landmarker.task', 'device': 'cuda'}
DEBUG: 0
KeyboardInterrupt
self.config: {'max_num_hands': 0, 'min_hand_detection_confidence': 0.1, 'min_tracking_confidence': 0.5, 'min_hand_presence_confidence': 0.5, 'running_mode': 'video', 'frame_rate': 30, 'model_asset_path': 'config/checkpoints/mediapipe/hand_landmarker.task', 'device': 'cuda'}
DEBUG: 0
Traceback (most recent call last):
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
self.config: {'max_num_hands': 0, 'min_hand_detection_confidence': 0.1, 'min_tracking_confidence': 0.5, 'min_hand_presence_confidence': 0.5, 'running_mode': 'video', 'frame_rate': 30, 'model_asset_path': 'config/checkpoints/mediapipe/hand_landmarker.task', 'device': 'cuda'}
DEBUG: 0
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/tools/02_mp_hand_detection.py", line 46, in run_mp_hand_detector
    detector = MPHandDetector(mp_config)
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/hocap_annotation/wrappers/mediapipe.py", line 14, in __init__
    self._detector = self._init_mp_hand_detector()
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/hocap_annotation/wrappers/mediapipe.py", line 40, in _init_mp_hand_detector
    return mp.tasks.vision.HandLandmarker.create_from_options(mp_options)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/site-packages/mediapipe/tasks/python/vision/hand_landmarker.py", line 364, in create_from_options
    return cls(
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: ValidatedGraphConfig Initialization failed.
ClipNormalizedRectVectorSizeCalculator: max_vec_size should be greater than or equal to 1.
ClipNormalizedRectVectorSizeCalculator: max_vec_size should be greater than or equal to 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/tools/02_mp_hand_detection.py", line 122, in detect_mp_handmarks
    mp_handmarks[serial] = future.result()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: ValidatedGraphConfig Initialization failed.
ClipNormalizedRectVectorSizeCalculator: max_vec_size should be greater than or equal to 1.
ClipNormalizedRectVectorSizeCalculator: max_vec_size should be greater than or equal to 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/tools/02_mp_hand_detection.py", line 227, in <module>
    detector.run()
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/tools/02_mp_hand_detection.py", line 210, in run
    self.detect_mp_handmarks()
  File "/home/wys/learning-compliant/crq_ws/HO-Cap-Annotation/tools/02_mp_hand_detection.py", line 111, in detect_mp_handmarks
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/concurrent/futures/process.py", line 780, in shutdown
    self._executor_manager_thread.join()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/wys/anaconda3/envs/hocap-annotation/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
